[project]
name = "echo-memory"
version = "0.1.0"
description = "Rytmiczna pamięć AI lokalnie"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
